export const imageSource = {
  bgImage: require('../assets/image/BGImage.png'),
  bgImage2: require('../assets/image/BgImage2.png'),
  check: require('../assets/image/check.png'),
  checkFill: require('../assets/image/checkFill.png'),
  checkMarkSquare: require('../assets/image/checkMarkSquare.png'),
  contactPeople: require('../assets/image/contactPeople.png'),
  copyRight: require('../assets/image/copyRight.png'),
  delete: require('../assets/image/delete.png'),
  logout: require('../assets/image/logout.png'),
  diploma: require('../assets/image/Diploma.png'),
  imageDemo1: require('../assets/image/imageDemo1.png'),
  imageDemo1black: require('../assets/image/imageDemo1&black.png'),
  imageDemo2: require('../assets/image/imageDemo2.png'),
  imageDemo3: require('../assets/image/imageDemo3.png'),
  moscow: require('../assets/image/Moscow.png'),
  pending: require('../assets/image/pending.png'),
  privacyPolicy: require('../assets/image/privacyPolicy.png'),
  profileLogo: require('../assets/image/profile-logo.png'),
  restorePasskey: require('../assets/image/restorePasskey.png'),
  termsOfUse: require('../assets/image/termsOfUse.png'),
  sphere: require('../assets/image/sphere.png'),
};
