export const string = {
  button: {
    add: 'Add',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    addNewDocument: 'Add new document',
    confirmAnApplication: 'Confirm an application',
    save: 'Save',
    accept: 'Accept',
    reject: 'Reject',
    rejectApplication: 'Reject application',
    leaveAReview: 'Leave a review',
    send: 'Send',
    cancel: 'Cancel',
    submitAnApplication: 'Submit an application',
    submitForReview: 'Submit For Review',
    endSession: 'End session',
    delete: 'Delete',
    exit: 'Exit',
  },
  auth: {
    life: 'Life',
    services: 'Services',
    helloWeWillHelp: 'Hello, we will help you find your specialist!',
  },
  forgotPassword: {
    restore: 'Restore',
    password: 'Password',
    enterYourEMail: 'Enter your E-mail',
    enterTheReceivedCode: 'Enter the received code',
    enterANewPass: 'Enter a new password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm New Password',
  },
  signIn: {
    email: 'E-Mail',
    password: 'Password',
    forgotPassword: 'Forgot Password?',
    dontHaveAnAccountYet: "Don't have an account yet?",
    createRightNow: 'Create right now',
  },
  signUp: {
    addYourPhoto: 'Add your photo',
    changePhoto: 'Change Photo',
    name: 'Name',
    chooseYourProfession: 'Choose your profession',
    chooseACountry: 'Choose a country',
    chooseYourCity: 'Choose your City',
    enterYourAddress: 'Enter your Address',
    yourPhoneNumber: 'Your phone number',
    addPhoneNumber: 'Add phone number',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    doYouAlreadyHave: 'Do you already have an account?',
  },
  home: {
    home: 'Home',
    moscow: 'Moscow',
    sphere: 'Sphere',
    bestOffers: 'Best Offers',
    allOffers: 'All Offers',
  },
  profile: {
    profile: 'Profile',
    aboutMe: 'About me',
    documents: 'Documents',
    viewAll: 'View All',
    spheresOfActivity: 'Spheres of activity',
    phoneNumber: 'Phone number',
    phoneNoPlaceholder: '+ 7 (495) 510 55 55',
    myReviews: 'My reviews',
  },
  profileSetting: {
    profile: 'Profile',
    changePhoto: 'Change Photo',
    name: 'Name',
    country: 'Country',
    cities: 'Cities',
    email: 'Email',
    aboutMe: 'About me',
    documents: 'Documents',
    add: 'Add',
    spheresOfActivity: 'Spheres of activity',
    chooseYourProfession: 'Choose your profession',
  },
  addDocument: {
    addDocument: 'Add Document',
    name: 'Name',
    documentType: 'Document Type',
    description: 'Description',
    changePhoto: 'Change Photo',
    attachPhoto: 'Attach Photo',
    openCamera: 'Open Camera',
    useLastPhoto: 'Use Last Photo Taken',
    chooseFromLibrary: 'Choose From Library',
  },
  viewAllDocument: {
    documents: 'Documents',
  },
  editAnApplication: {
    editAnApplication: 'Edit an Application',
    viewPhoto: 'View photo',
  },
  createNewDocument: {
    createAnApplication: 'Create an Application',
    chooseYourProfession: 'Choose your profession',
    phoneNoPlaceholder: '+ 7 (495) 510 55 55',
    description: 'Description',
    viewPhoto: 'View photo',
    attachPhoto: 'Attach photo',
  },
  viewAllPhoto: {
    viewPhoto: 'View Photos',
  },
  favourite: { favourites: 'Favourites' },
  application: { applications: 'Applications' },
  created: {
    applicationCompleted: 'Application completed',
    leaveAReview: 'Leave a review',
    yourReview: 'Your Review',
    yourMark: 'Your Mark',
  },

  notification: {
    notification: 'Notification',
  },
  setting: {
    settings: 'Settings',
    areYouSureYouWantoDelete: 'Are you sure you want to delete your account?',
    thisActionIsIrreversible: 'This action is irreversible',

    areYouSureYouWantToExit: 'Are you sure you want to exit?',
    youWillHaveToLogInAgain: 'You will have to log in again',
  },

  copyRight: {
    copyRight: 'Copy Right',
  },
  privacyPolicy: {
    privacyPolicy: 'Privacy Policy',
  },
  communityRules: {
    communityRules: 'Community Rules',
  },
  termOfUse: {
    termOfUse: 'Term Of Use',
  },

  mapscreen: {
    nextToMe: 'Next to me',
  },
};
